services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - node

  node:
    entrypoint: dockerize -wait tcp://mysql:3306
    command: npm start
    container_name: node
    build:
      context: ./node
    ports:
      - "3000:3000"
    volumes:
      - "./node:/app"
    depends_on:
      - mysql
  
  mysql:
    image: mysql:5.7.38-debian
    command: --innodb-use-native-aio=0
    container_name: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_ROOT_PASSWORD=root
    restart: always
  
