services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    networks:
      - node-network
    ports:
      - "8080:80"
    restart: always
    tty: true
    entrypoint: dockerize -wait http://node:3000 -timeout 10s /docker-entrypoint.sh
    command: nginx -g "daemon off;"
    depends_on:
      - node

  node:
    build:
      context: node
    container_name: node
    networks:
      - node-network
    tty: true
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 10s sh -c "npm ci && node index.js"
    volumes:
      - "./node:/app"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.1.0
    container_name: mysql
    networks:
      - node-network
    volumes:
      - mysql-volume:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=node-db
      - MYSQL_ROOT_PASSWORD=root
    restart: always
    tty: true

networks:
  node-network:
    driver: bridge

volumes:
  mysql-volume:
